config/routes.rb
Web2automator::Application.routes.draw do
  root :to => "projects#index"
  resources :projects
  resources :project_keywords
  resources :keyword_web2s
  resources :web2s
  resources :keywords

  get 'create_facebook_profile' => 'keywords#create_facebook_profile'
  get 'place_facebook_link' => 'keywords#place_facebook_link'
  #
  get 'create_plus_profile' => 'keywords_plus_profile'
  get 'place_plus_link' => 'keywords#place_plus_link'
  #
  get 'create_linkedin_profile' => 'keywords#create_linkedin_profile'
  get 'place_linkedin_link' => 'keywords#place_linkedin_link'
  #
  get 'create_youtube_profile' => 'keywords#create_youtube_profile'
  get 'place_youtube_link' => 'keywords#place_youtube_link'
  #
  get 'create_profiles' => 'keywords#create_profiles', as: 'create_profiles'
  get 'create_links' => 'keywords#create_links', as: 'create_links'
  #
  get 'create_twitter_profile' => 'keywords#create_twitter_profile'
  get 'place_twitter_link' => 'keywords#place_twitter_link'
  #
  get 'create_pinterest_profile' => 'keywords#create_pinterest_profile'
  get 'place_pinterest_link' => 'keywords#place_pinterest_link'
  #
  get 'create_instagram_profile' => 'keywords#create_instagram_profile'
  get 'place_instagram_link' => 'keywords#place_instagram_link'
  #
  get 'create_myspace_profile' => 'keywords#create_myspace_profile'
  get 'place_myspace_link' => 'keywords#place_myspace_link'
  #
  get 'create_tumblr_profile' => 'keywords#create_tumblr_profile'
  get 'place_tumblr_link' => 'keywords#place_tumblr_link'
  #
  get 'create_flickr_profile' => 'keywords#create_flickr_profile'
  get 'place_flickr_link' => 'keywords#place_flickr_link'
  #
  get 'create_quora_profile' => 'keywords#create_quora_profile'
  get 'place_quora_link' => 'keywords#place_quora_link'
  #
  get 'create_medium_profile' => 'keywords#create_medium_profile'
  get 'place_medium_link' => 'keywords#place_medium_link'
  #
  get 'create_github_profile' => 'keywords#create_github_profile'
  get 'place_github_link' => 'keywords#place_github_link'
  #
  get 'create_vimeo_profile' => 'keywords#create_vimeo_profile'
  get 'place_vimeo_link' => 'keywords#place_vimeo_link'
  #
  get 'create_usgbc_profile' => 'keywords#create_usgbc_profile'
  get 'place_usgbc_link' => 'keywords#place_usgbc_link'
  #
  get 'create_eventful_profile' => 'keywords#create_eventful_profile'
  get 'place_eventful_link' => 'keywords#place_eventful_link'
  #
  get 'create_about_profile' => 'keywords#create_about_profile'
  get 'place_about_link' => 'keywords#place_about_link'
  #
  get 'create_askbook_profile' => 'keywords#create_askbook_profile'
  get 'place_askbook_link' => 'keywords#place_askbook_link'
  #
  get 'create_yelp_profile' => 'keywords#create_yelp_profile'
  get 'place_yelp_link' => 'keywords#place_yelp_link'
  #
  get 'create_goodreads_profile' => 'keywords#create_goodreads_profile'
  get 'place_goodreads_link' => 'keywords#place_goodreads_link'
  #
  get 'create_behance_profile' => 'keywords#create_behance_profile'
  get 'place_behance_link' => 'keywords#place_behance_link'
  #
  get 'create_codecademy_profile' => 'keywords#create_codecademy_profile'
  get 'place_codecademy_link' => 'keywords#place_codecademy_link'
  #
  get 'create_foursquare_profile' => 'keywords#create_foursquare_profile'
  get 'place_foursquare_link' => 'keywords#place_foursquare_link'
  #
  get 'create_armorgames_profile' => 'keywords#create_armorgames_profile'
  get 'place_armorgames_link' => 'keywords#place_armorgames_link'
  #
  get 'create_meetup_profile' => 'keywords#create_meetup_profile'
  get 'place_meetup_link' => 'keywords#place_meetup_link'
  #
  get 'create_soundcloud_profile' => 'keywords#create_soundcloud_profile'
  get 'place_soundcloud_link' => 'keywords#place_soundcloud_link'
  #
  get 'create_soup_profile' => 'keywords#create_soup_profile'
  get 'place_soup_link' => 'keywords#place_soup_link'
  #
  get 'create_500px_profile' => 'keywords#create_500px_profile'
  get 'place_500px_link' => 'keywords#place_500px_link'
  #
  get 'create_deviantart_profile' => 'keywords#create_deviantart_profile'
  get 'place_deviantart_link' => 'keywords#place_deviantart_link'
  #
  get 'create_pearltrees_profile' => 'keywords#create_pearltrees_profile'
  get 'place_pearltrees_link' => 'keywords#place_pearltrees_link'
  #
  get 'create_disqus_profile' => 'keywords#create_disqus_profile'
  get 'place_disqus_link' => 'keywords#place_disqus_link'
  #
  get 'create_instructables_profile' => 'keywords#create_instructables_profile'
  get 'place_instructables_link' => 'keywords#place_instructables_link'
  #
  get 'create_livejournal_profile' => 'keywords#create_livejournal_profile'
  get 'place_livejournal_link' => 'keywords#place_livejournal_link'
  #
  get 'create_allnumis_profile' => 'keywords#create_allnumis_profile'
  get 'place_allnumis_link' => 'keywords#place_allnumis_link'
  #
  get 'create_audimated_profile' => 'keywords#create_audimated_profile'
  get 'place_audimated_link' => 'keywords#place_audimated_link'
  #
  get 'create_care2_profile' => 'keywords#create_care2_profile'
  get 'place_care2_link' => 'keywords#place_care2_link'
  #
  get 'create_colourlovers_profile' => 'keywords#create_colourlovers_profile'
  get 'place_colourlovers_link' => 'keywords#place_colourlovers_link'
  #
  get 'create_creativemarket_profile' => 'keywords#create_creativemarket_profile'
  get 'place_creativemarket_link' => 'keywords#place_creativemarket_link'
  #
  get 'create_designspiration_profile' => 'keywords#create_designspiration_profile'
  get 'place_designspiration_link' => 'keywords#place_designspiration_link'
  #
  get 'create_dreamwidth_profile' => 'keywords#create_dreamwidth_profile'
  get 'place_dreamwidth_link' => 'keywords#place_dreamwidth_link'
  #
  get 'create_ello_profile' => 'keywords#create_ello_profile'
  get 'place_ello_link' => 'keywords#place_ello_link'
  #
  get 'create_gapyear_profile' => 'keywords#create_gapyear_profile'
  get 'place_gapyear_link' => 'keywords#place_gapyear_link'
  #
  get 'create_bagtheweb_profile' => 'keywords#create_bagtheweb_profile'
  get 'place_bagtheweb_link' => 'keywords#place_bagtheweb_link'
  #
  get 'create_pastebin_profile' => 'keywords#create_pastebin_profile'
  get 'place_pastebin_link' => 'keywords#place_pastebin_link'
  #
  get 'create_plurk_profile' => 'keywords#create_plurk_profile'
  get 'place_plurk_link' => 'keywords#place_plurk_link'
  #
  get 'create_weheartit_profile' => 'keywords#create_weheartit_profile'
  get 'place_weheartit_link' => 'keywords#place_weheartit_link'
  #
  get 'create_gravatar_profile' => 'keywords#create_gravatar_profile'
  get 'place_gravatar_link' => 'keywords#place_gravatar_link'
  #
  get 'create_adsoftheworld_profile' => 'keywords#create_adsoftheworld_profile'
  get 'place_adsoftheworld_link' => 'keywords#place_adsoftheworld_link'
  #
  get 'create_ask_profile' => 'keywords#create_ask_profile'
  get 'place_ask_link' => 'keywords#place_ask_link'
  #
  get 'create_authorstream_profile' => 'keywords#create_authorstream_profile'
  get 'place_authorstream_link' => 'keywords#place_authorstream_link'
  #
  get 'create_codeproject_profile' => 'keywords#create_codeproject_profile'
  get 'place_codeproject_link' => 'keywords#place_codeproject_link'
  #
  get 'create_feedspot_profile' => 'keywords#create_feedspot_profile'
  get 'place_feedspot_link' => 'keywords#place_feedspot_link'
  #
  get 'create_filmow_profile' => 'keywords#create_filmow_profile'
  get 'place_filmow_link' => 'keywords#place_filmow_link'
  #
  get 'create_hawkee_profile' => 'keywords#create_hawkee_profile'
  get 'place_hawkee_link' => 'keywords#place_hawkee_link'
  #
  get 'create_issuu_profile' => 'keywords#create_issuu_profile'
  get 'place_issuu_link' => 'keywords#place_issuu_link'
  #
  get 'create_kweekweek_profile' => 'keywords#create_kweekweek_profile'
  get 'place_kweekweek_link' => 'keywords#place_kweekweek_link'
  #
  get 'create_logopond_profile' => 'keywords#create_logopond_profile'
  get 'place_logopond_link' => 'keywords#place_logopond_link'
  #
  get 'create_fontspace_profile' => 'keywords#create_fontspace_profile'
  get 'place_fontspace_link' => 'keywords#place_fontspace_link'
  #
  get 'create_audioboom_profile' => 'keywords#create_audioboom_profile'
  get 'place_audioboom_link' => 'keywords#place_audioboom_link'
  #
  get 'create_nationalgeographic_profile' => 'keywords#create_nationalgeographic_profile'
  get 'place_nationalgeographic_link' => 'keywords#place_nationalgeographic_link'
  #
  get 'create_myvidster_profile' => 'keywords#create_myvidster_profile'
  get 'place_myvidster_link' => 'keywords#place_myvidster_link'
  #
  get 'create_angel_profile' => 'keywords#create_angel_profile'
  get 'place_angel_link' => 'keywords#place_angel_link'
  #
  get 'create_zillow_profile' => 'keywords#create_zillow_profile'
  get 'place_zillow_link' => 'keywords#place_zillow_link'
  #
  get 'create_wordpress_profile' => 'keywords#create_wordpress_profile'
  get 'place_wordpress_link' => 'keywords#place_wordpress_link'
  #
  get 'create_steepster_profile' => 'keywords#create_steepster_profile'
  get 'place_steepster_link' => 'keywords#place_steepster_link'
  #
  get 'create_ted_profile' => 'keywords#create_ted_profile'
  get 'place_ted_link' => 'keywords#place_ted_link'
  #
  get 'create_udemy_profile' => 'keywords#create_udemy_profile'
  get 'place_udemy_link' => 'keywords#place_udemy_link'
  #
  get 'create_sketchfab_profile' => 'keywords#create_sketchfab_profile'
  get 'place_sketchfab_link' => 'keywords#place_sketchfab_link'
  #
  get 'create_getsatisfaction_profile' => 'keywords#create_getsatisfaction_profile'
  get 'place_getsatisfaction_link' => 'keywords#place_getsatisfaction_link'
  #
  get 'create_speakerdeck_profile' => 'keywords#create_speakerdeck_profile'
  get 'place_speakerdeck_link' => 'keywords#place_speakerdeck_link'
  #
  get 'create_accountingweb_profile' => 'keywords#create_accountingweb_profile'

app/models/keyword.rb
class Keyword < ActiveRecord::Base
end

app/helpers/keywords_helper.rb
module KeywordsHelper
end

app/views/keywords/_form.html.erb
<%= form_for(@keyword) do |f| %>
  <% if @keyword.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@keyword.errors.count, "error") %> prohibited this keyword from being saved:</h2>

      <ul>
      <% @keyword.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :keyword %><br />
    <%= f.text_field :keyword, class: "form-control", style: 'width: 40%' %>
  </div>
  <div class="field">
    <%= f.label :link %><br />
    <%= f.text_field :link, class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email, class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.text_field :password, class: "form-control", style: 'width: 40%' %>
  </div>
  <div class="field">
    <%= f.label :password2 %><br />
    <%= f.text_field :password2, class: "form-control", style: 'width: 40%' %>
  </div>
  <div class="field">
    <%= f.label :description %><br /> Please do not use single quotes, but use ` instead;  else it will break the code
    <%= f.text_area :description, class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label :logo_path %><br />
    <%= f.text_field :logo_path, class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label :small_logo_path %> (Less than 500x500px) <br />
    <%= f.text_field :small_logo_path, class: "form-control" %>
  </div>
 
  <div class="field">
    <%= f.label :anchor_text %><br />
    <%= f.text_field :anchor_text, class: "form-control", style: 'width: 40%' %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_field :address, class: "form-control", style: 'width: 40%' %>
  </div>
  <br/>
  <div class="field">
    <%= f.label :city %><br />
    <%= f.text_field :city, class: "form-control", style: 'width: 40%' %>
  </div>
  <br/>
  <div class="field">
    <%= f.label :state %><br />
    <%= f.text_field :state, class: "form-control", style: 'width: 40%' %>
  </div>
  <br/>
  <div class="field">
    <%= f.label :zipcode %><br />
    <%= f.text_field :zipcode, class: "form-control", style: 'width: 40%' %>
  </div>
  <br/>
   <div class="field">
    <%= f.label :country %><br />
    <%= f.text_field :country, class: "form-control", style: 'width: 40%' %>
  </div>
  <br/>
 
  <div class="actions">
    <%= f.submit class: "btn btn-primary" %>
  </div>
  <br/>
<% end %>

app/views/keywords/place_nationalgeographic_link.html.erb
<%
require 'rubygems'
require 'watir'

browser = Watir::Browser.new
profiles = []
@keyword = Keyword.find(params[:keyword_id])

#NationalGeographic
kw2 = KeywordWeb2.where(keyword_id: @keyword.id, web2_id: Web2.where("url LIKE ?", "%nationalgeographic.com%").first.id)
#if kw2.length < 1
    # Logs in and adds link
    browser.goto 'https://members.nationalgeographic.com/account/login'
    browser.text_field(name: 'username').set @keyword.email
    browser.text_field(name: 'password').set @keyword.password2
    browser.button(text: 'Sign In').click
    sleep 2
    browser.goto 'https://members.nationalgeographic.com/settings/public-profile/'
    browser.execute_script("window.scrollBy(0,800)")
    browser.text_field(id: 'personal-site').set @keyword.link
    twitter = KeywordWeb2.where(keyword_id: @keyword.id).where('link LIKE ?', '%twitter.com%')
    twitter = twitter.first.link.gsub('https://twitter.com/', '').tr('/', '') if twitter.first
    facebook = KeywordWeb2.where(keyword_id: @keyword.id).where('link LIKE ?', '%facebook.com%')
    facebook = facebook.first.link.gsub('https://www.facebook.com/', '').tr('/', '') if facebook.first
    tumblr = KeywordWeb2.where(keyword_id: @keyword.id).where('link LIKE ?', '%tumblr.com%')
    tumblr = tumblr.first.link.gsub('https://tumblr.com/', '') if tumblr.first
    instagram = KeywordWeb2.where(keyword_id: @keyword.id).where('link LIKE ?', '%instagram.com%')
    instagram = instagram.first.link.gsub('https://www.instagram.com/', '').tr('/', '') if instagram.first
    # Place socials
    browser.text_field(name: 'followTwitter').set twitter unless twitter.empty?
    browser.text_field(name: 'followFacebook').set facebook unless facebook.empty?
    browser.text_field(name: 'followTumblr').set tumblr unless tumblr.empty?
    browser.text_field(name: 'followInstagram').set instagram unless instagram.empty?
    browser.textarea(name: 'bio').set @keyword.description
    browser.execute_script("alert(\"Please make sure socials are good continue. You got 12 seconds to do so..\")")
    sleep 15
    browser.execute_script("window.scrollBy(0,1200)")
    browser.link(text: 'Save Changes').click
    sleep 1
    browser.execute_script("alert(\"Please click on Public Profile. You got 5 seconds to do so..\")")
    sleep 8
    # Save link
    profiles << browser.url
    keyword_web2 = KeywordWeb2.find_or_create_by_keyword_id_and_web2_id(keyword_id: @keyword.id, web2_id: Web2.where("url LIKE ?", "%nationalgeographic.com%").first.id)
    keyword_web2.update_attributes(link: browser.url)
    browser.close
#else
#   profiles << kw2.first.link
#end
%>

</br></br>
Congrats, nationalgeographic link was placed!

<% profiles.each do |p| %>
    <%= "<a href=\"#{p}\">#{p}</a>".html_safe %>
    </br>
<% end %>

</br></br>

<%= link_to 'Back', keyword_path(@keyword) %>

app/views/keywords/place_slashdot_link.html.erb
<%
require 'rubygems'
require 'watir'

browser = Watir::Browser.new
profiles = []
@keyword = Keyword.find(params[:keyword_id])

#SlashDot
kw2 = KeywordWeb2.where(keyword_id: @keyword.id, web2_id: Web2.where("url LIKE ?", "slashdot.org%").first.id)
#if kw2.length < 1
    browser.goto 'https://slashdot.org/'
    browser.span(text: 'Login').click
    browser.text_field(name: 'unickname').set @keyword.keyword
    browser.execute_script("alert(\"Please fix username if necessary.\")")
    sleep 10
    browser.text_field(name: 'upasswd').set @keyword.password
    browser.input(name: 'userlogin').click
    browser.link(text: 'Submit').click
    browser.text_field(name: 'title').set @keyword.anchor_text
    browser.textarea(name: 'introtext').set @keyword.description
    browser.text_field(name: 'url').set @keyword.link
    browser.input(id: 'edit-preview-button').click
    browser.execute_script("alert(\"Please solve CAPTCHA.\")")
    sleep 10
    browser.execute_script("window.scrollBy(0,150)")
    browser.input(id: 'edit-edit-save').click if browser.input(id: 'edit-edit-save').exists?
    browser.execute_script("alert(\"Please navigate to profile.\")")
    sleep 10
    # Save link
    profiles << browser.url
    keyword_web2 = KeywordWeb2.find_or_create_by_keyword_id_and_web2_id(keyword_id: @keyword.id, web2_id: Web2.where("url LIKE ?", "slashdot.org%").first.id)
    keyword_web2.update_attributes(link: browser.url)

   browser.close
#else
#   profiles << kw2.first.link
#end
%>

</br></br>
Congrats, slashdot was placed!

<% profiles.each do |p| %>
    <%= "<a href=\"#{p}\">#{p}</a>".html_safe %>
    </br>
<% end %>

</br></br>

<%= link_to 'Back', keyword_path(@keyword) %>

app/views/keywords/place_soundcloud_link.html.erb
<%
require 'rubygems'
require 'watir'

browser = Watir::Browser.new
profiles = []

#SoundCloud
kw2 = KeywordWeb2.where(keyword_id: @keyword.id, web2_id: Web2.where("url LIKE ?", "%soundcloud%").first.id)
#if kw2.length < 1
    # Logs in and adds link
    browser.goto 'https://soundcloud.com'
    browser.execute_script("alert(\"Please do this one manually to continue.. Auto bot detection is HIGH!!\")")
    sleep(10)
    #profiles << browser.url
    #keyword_web2 = KeywordWeb2.find_or_create_by_keyword_id_and_web2_id(keyword_id: @keyword.id, web2_id: Web2.where("url LIKE ?", "%soundcloud%").first.id)
    #keyword_web2.update_attributes(link: browser.url)
    browser.close
#else
#   profiles << kw2.first.link
#end
%>

</br></br>
Congrats, soundcloud link was placed!

<% profiles.each do |p| %>
    <%= "<a href=\"#{p}\">#{p}</a>".html_safe %>
    </br>
<% end %>

</br></br>

<%= link_to 'Back', keyword_path(@keyword) %>

app/views/keywords/place_trainingzone_link.html.erb
<%
require 'rubygems'
require 'watir'

browser = Watir::Browser.new
profiles = []
@keyword = Keyword.find(params[:keyword_id])

#TrainingZone
kw2 = KeywordWeb2.where(keyword_id: @keyword.id, web2_id: Web2.where("url LIKE ?", "%trainingzone.co%").first.id)
#if kw2.length < 1
    browser.goto 'https://www.trainingzone.co.uk/user/login'
    browser.execute_script("window.scrollBy(0,700)")
    browser.text_field(id: 'edit-name').set @keyword.email
    browser.text_field(id: 'edit-pass').set @keyword.password
    browser.button(text: 'Sign in').click
    sleep 2
    browser.execute_script("alert(\"Please click MY ACCOUNT.\")")
    sleep 3
    browser.execute_script("alert(\"Please upload pic.\")")
    sleep 33

    browser.execute_script("window.scrollBy(0,1400)")

    description = 'Place this in description: '+ @keyword.description
    browser.execute_script("var test = '#{description}';alert(test);")

    sleep 9
    browser.text_field(id: 'edit-field-website-und-0-value').set @keyword.link
    browser.execute_script("window.scrollBy(0,700)")

    twitter = KeywordWeb2.where(keyword_id: @keyword.id).where('link LIKE ?', '%twitter.com%')
    twitter = twitter.first.link if twitter.first
    browser.text_field(id: 'edit-field-twitter-und-0-value').set twitter unless twitter.empty?

    linkedin = KeywordWeb2.where(keyword_id: @keyword.id).where('link LIKE ?', '%linkedin.com%')
    linkedin = linkedin.first.link if linkedin.first
    browser.text_field(id: 'edit-field-linkedin-und-0-value').set linkedin unless linkedin.empty?

    facebook = KeywordWeb2.where(keyword_id: @keyword.id).where('link LIKE ?', '%facebook.com%')
    facebook = facebook.first.link if facebook.first
    browser.text_field(id: 'edit-field-facebook-und-0-value').set facebook unless facebook.empty?

    google = KeywordWeb2.where(keyword_id: @keyword.id).where('link LIKE ?', '%plus.google.com%')
    google = google.first.link if google.first
    browser.text_field(id: 'edit-field-google-und-0-value').set google unless google.empty?

    browser.execute_script("window.scrollBy(0,2000)")
    browser.input(id: 'edit-submit').click
    sleep 2
    browser.execute_script("alert(\"Please click VIEW MY PUBLIC PROFILE.\")")
    sleep 5
    # Save link
    profiles << browser.url
    keyword_web2 = KeywordWeb2.find_or_create_by_keyword_id_and_web2_id(keyword_id: @keyword.id, web2_id: Web2.where("url LIKE ?", "%trainingzone.co%").first.id)
    keyword_web2.update_attributes(link: browser.url)

    browser.close
#else
#   profiles << kw2.first.link
#end
%>

</br></br>
Congrats, trainingzone was placed!

<% profiles.each do |p| %>
    <%= "<a href=\"#{p}\">#{p}</a>".html_safe %>
    </br>
<% end %>

</br></br>

<%= link_to 'Back', keyword_path(@keyword) %>

app/views/keywords/place_wattpad_link.html.erb
<%
require 'rubygems'
require 'watir'

browser = Watir::Browser.new
profiles = []
@keyword = Keyword.find(params[:keyword_id])

#Wattpad
kw2 = KeywordWeb2.where(keyword_id: @keyword.id, web2_id: Web2.where("url LIKE ?", "wattpad.com%").first.id)
#if kw2.length < 1
    browser.goto 'https://www.wattpad.com/login'
    browser.text_field(id: 'login-user').set @keyword.email.tr('.', '')
    browser.text_field(id: 'login-password').set @keyword.password
    browser.input(value: 'Log in').click
    browser.goto 'https://www.wattpad.com/user_profile'
    browser.text_field(name: 'realname').set @keyword.anchor_text
    browser.text_field(name: 'birthdate').set '01-01-1980'
    browser.select_list(name: 'gender').select_value('M')
    browser.text_field(name: 'location').set @keyword.city
    browser.text_field(name: 'website').set @keyword.link
    browser.textarea(name: 'about').set @keyword.description
    browser.link(id: 'account_save').click

    browser.button(id: 'changeAvatar').click
    browser.file_field(name: 'avatar').set @keyword.logo_path
    #browser.button(id: 'changeBackground').click
    #browser.file_field(name: 'profilebg').set @keyword.logo_path
    browser.link(id: 'account_save').click

    browser.div(class: 'avatar avatar-sm').click
    browser.link(text: 'My Profile').click
    # Save link
    profiles << browser.url
    keyword_web2 = KeywordWeb2.find_or_create_by_keyword_id_and_web2_id(keyword_id: @keyword.id, web2_id: Web2.where("url LIKE ?", "wattpad.com%").first.id)
    keyword_web2.update_attributes(link: browser.url)

   browser.close
#else
#   profiles << kw2.first.link
#end
%>

</br></br>
Congrats, wattpad was placed!

<% profiles.each do |p| %>
    <%= "<a href=\"#{p}\">#{p}</a>".html_safe %>
    </br>
<% end %>

</br></br>

<%= link_to 'Back', keyword_path(@keyword) %>

app/views/keywords/place_zillow_link.html.erb
<%
require 'rubygems'
require 'watir'

browser = Watir::Browser.new
profiles = []
@keyword = Keyword.find(params[:keyword_id])

#Zillow
kw2 = KeywordWeb2.where(keyword_id: @keyword.id, web2_id: Web2.where("url LIKE ?", "%zillow.com%").first.id)
#if kw2.length < 1
    # Logs in and adds link
    browser.goto 'https://www.zillow.com/user/acct/login/'
    sleep 20
    browser.text_field(id: 'email').set @keyword.email
    browser.text_field(id: 'password').set @keyword.password
    browser.button(text: 'Sign in').click
    browser.goto 'https://www.zillow.com/user/EditProfile.htm'
    browser.text_field(id: 'firstName').set @keyword.anchor_text.split[0]
    browser.text_field(id: 'lastName').set @keyword.anchor_text.split[1]
    browser.file_field(id: 'input_imgupload').set(@keyword.logo_path)
    browser.button(text: 'Submit').click
    sleep 2
    browser.goto 'https://www.zillow.com/myzillow/Profile.htm#profile-aboutme-block'
    browser.textarea(id: 'rte-aboutMeTextArea').set @keyword.description

    browser.execute_script("alert(\"Please place link to continue. You got 10 seconds to do so..\")")
    sleep 15
    Watir::Wait.until(1800) { browser.text.include? 'Boom Shakalaka!' }

    # Save link
    profiles << browser.url
    keyword_web2 = KeywordWeb2.find_or_create_by_keyword_id_and_web2_id(keyword_id: @keyword.id, web2_id: Web2.where("url LIKE ?", "%zillow.com%").first.id)
    keyword_web2.update_attributes(link: browser.url)
    browser.close
#else
#   profiles << kw2.first.link
#end
%>

</br></br>
Congrats, zillow link was placed!

<% profiles.each do |p| %>
    <%= "<a href=\"#{p}\">#{p}</a>".html_safe %>
    </br>
<% end %>

</br></br>

<%= link_to 'Back', keyword_path(@keyword) %>